# Generated by Django 3.1.7 on 2021-05-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0002_auto_20210518_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Property Law', 'Property Law'), ('Environment Law', 'Environment Law'), ('Corruption Law', 'Corruption Law'), ('Civil Law', 'Civil Law'), ('Personal Law', 'Personal Law'), ('Financial Law', 'Financial Law'), ('Healthcare Law', 'Healthcare Law'), ('Criminal Law', 'Criminal Law'), ('Social Law', 'Social Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Education Law', 'Education Law'), ('Labour Law', 'Labour Law')], default='1', max_length=100),
        ),
    ]
