# Generated by Django 3.1.7 on 2021-05-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0004_auto_20210518_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Personal Law', 'Personal Law'), ('Property Law', 'Property Law'), ('Labour Law', 'Labour Law'), ('Education Law', 'Education Law'), ('Civil Law', 'Civil Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Social Law', 'Social Law'), ('Corruption Law', 'Corruption Law'), ('Environment Law', 'Environment Law'), ('Financial Law', 'Financial Law'), ('Healthcare Law', 'Healthcare Law'), ('Criminal Law', 'Criminal Law')], default='1', max_length=100),
        ),
    ]
