# Generated by Django 3.1.7 on 2021-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0006_auto_20210522_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Property Law', 'Property Law'), ('Financial Law', 'Financial Law'), ('Civil Law', 'Civil Law'), ('Healthcare Law', 'Healthcare Law'), ('Labour Law', 'Labour Law'), ('Personal Law', 'Personal Law'), ('Social Law', 'Social Law'), ('Environment Law', 'Environment Law'), ('Corruption Law', 'Corruption Law'), ('Criminal Law', 'Criminal Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Education Law', 'Education Law')], default='1', max_length=100),
        ),
    ]
