# Generated by Django 3.1.7 on 2021-06-16 09:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0007_auto_20210522_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprofile',
            name='case_law',
            field=models.CharField(choices=[('Labour Law', 'Labour Law'), ('Property Law', 'Property Law'), ('Healthcare Law', 'Healthcare Law'), ('Education Law', 'Education Law'), ('Criminal Law', 'Criminal Law'), ('Personal Law', 'Personal Law'), ('Social Law', 'Social Law'), ('Environment Law', 'Environment Law'), ('Corruption Law', 'Corruption Law'), ('Civil Law', 'Civil Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Financial Law', 'Financial Law')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Labour Law', 'Labour Law'), ('Property Law', 'Property Law'), ('Healthcare Law', 'Healthcare Law'), ('Education Law', 'Education Law'), ('Criminal Law', 'Criminal Law'), ('Personal Law', 'Personal Law'), ('Social Law', 'Social Law'), ('Environment Law', 'Environment Law'), ('Corruption Law', 'Corruption Law'), ('Civil Law', 'Civil Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Financial Law', 'Financial Law')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
