# Generated by Django 3.1.7 on 2021-06-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0008_auto_20210616_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='caseprofile',
            name='case_law',
            field=models.CharField(choices=[('Civil Law', 'Civil Law'), ('Property Law', 'Property Law'), ('Criminal Law', 'Criminal Law'), ('Social Law', 'Social Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Labour Law', 'Labour Law'), ('Corruption Law', 'Corruption Law'), ('Financial Law', 'Financial Law'), ('Environment Law', 'Environment Law'), ('Personal Law', 'Personal Law'), ('Healthcare Law', 'Healthcare Law'), ('Education Law', 'Education Law')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Civil Law', 'Civil Law'), ('Property Law', 'Property Law'), ('Criminal Law', 'Criminal Law'), ('Social Law', 'Social Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Labour Law', 'Labour Law'), ('Corruption Law', 'Corruption Law'), ('Financial Law', 'Financial Law'), ('Environment Law', 'Environment Law'), ('Personal Law', 'Personal Law'), ('Healthcare Law', 'Healthcare Law'), ('Education Law', 'Education Law')], default='1', max_length=100),
        ),
    ]
