# Generated by Django 3.1.7 on 2021-06-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0009_auto_20210616_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprofile',
            name='case_law',
            field=models.CharField(choices=[('Environment Law', 'Environment Law'), ('Personal Law', 'Personal Law'), ('Education Law', 'Education Law'), ('Social Law', 'Social Law'), ('Financial Law', 'Financial Law'), ('Criminal Law', 'Criminal Law'), ('Healthcare Law', 'Healthcare Law'), ('Labour Law', 'Labour Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Property Law', 'Property Law'), ('Civil Law', 'Civil Law'), ('Corruption Law', 'Corruption Law')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Environment Law', 'Environment Law'), ('Personal Law', 'Personal Law'), ('Education Law', 'Education Law'), ('Social Law', 'Social Law'), ('Financial Law', 'Financial Law'), ('Criminal Law', 'Criminal Law'), ('Healthcare Law', 'Healthcare Law'), ('Labour Law', 'Labour Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Property Law', 'Property Law'), ('Civil Law', 'Civil Law'), ('Corruption Law', 'Corruption Law')], default='1', max_length=100),
        ),
    ]
