# Generated by Django 3.1.7 on 2021-06-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0010_auto_20210616_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprofile',
            name='case_law',
            field=models.CharField(choices=[('Criminal Law', 'Criminal Law'), ('Labour Law', 'Labour Law'), ('Social Law', 'Social Law'), ('Personal Law', 'Personal Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Corruption Law', 'Corruption Law'), ('Financial Law', 'Financial Law'), ('Environment Law', 'Environment Law'), ('Healthcare Law', 'Healthcare Law'), ('Civil Law', 'Civil Law'), ('Property Law', 'Property Law'), ('Education Law', 'Education Law')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Criminal Law', 'Criminal Law'), ('Labour Law', 'Labour Law'), ('Social Law', 'Social Law'), ('Personal Law', 'Personal Law'), ('Cyber Crime Law', 'Cyber Crime Law'), ('Corruption Law', 'Corruption Law'), ('Financial Law', 'Financial Law'), ('Environment Law', 'Environment Law'), ('Healthcare Law', 'Healthcare Law'), ('Civil Law', 'Civil Law'), ('Property Law', 'Property Law'), ('Education Law', 'Education Law')], default='1', max_length=100),
        ),
    ]
