# Generated by Django 3.1.7 on 2024-05-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0011_auto_20210616_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprofile',
            name='case_law',
            field=models.CharField(choices=[('Cyber Crime Law', 'Cyber Crime Law'), ('Healthcare Law', 'Healthcare Law'), ('Civil Law', 'Civil Law'), ('Criminal Law', 'Criminal Law'), ('Financial Law', 'Financial Law'), ('Labour Law', 'Labour Law'), ('Property Law', 'Property Law'), ('Education Law', 'Education Law'), ('Corruption Law', 'Corruption Law'), ('Social Law', 'Social Law'), ('Personal Law', 'Personal Law'), ('Environment Law', 'Environment Law')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Cyber Crime Law', 'Cyber Crime Law'), ('Healthcare Law', 'Healthcare Law'), ('Civil Law', 'Civil Law'), ('Criminal Law', 'Criminal Law'), ('Financial Law', 'Financial Law'), ('Labour Law', 'Labour Law'), ('Property Law', 'Property Law'), ('Education Law', 'Education Law'), ('Corruption Law', 'Corruption Law'), ('Social Law', 'Social Law'), ('Personal Law', 'Personal Law'), ('Environment Law', 'Environment Law')], default='1', max_length=100),
        ),
    ]
