# Generated by Django 3.1.7 on 2024-05-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkeel', '0012_auto_20240515_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprofile',
            name='case_law',
            field=models.CharField(choices=[('Personal Law', 'Personal Law'), ('Criminal Law', 'Criminal Law'), ('Financial Law', 'Financial Law'), ('Corruption Law', 'Corruption Law'), ('Property Law', 'Property Law'), ('Labour Law', 'Labour Law'), ('Civil Law', 'Civil Law'), ('Healthcare Law', 'Healthcare Law'), ('Environment Law', 'Environment Law'), ('Social Law', 'Social Law'), ('Education Law', 'Education Law'), ('Cyber Crime Law', 'Cyber Crime Law')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Personal Law', 'Personal Law'), ('Criminal Law', 'Criminal Law'), ('Financial Law', 'Financial Law'), ('Corruption Law', 'Corruption Law'), ('Property Law', 'Property Law'), ('Labour Law', 'Labour Law'), ('Civil Law', 'Civil Law'), ('Healthcare Law', 'Healthcare Law'), ('Environment Law', 'Environment Law'), ('Social Law', 'Social Law'), ('Education Law', 'Education Law'), ('Cyber Crime Law', 'Cyber Crime Law')], default='1', max_length=100),
        ),
    ]
